const moviesArray = [
"A Trip to the Moon", 
"The Great Train Robbery", 
"Les Vampires", 
"The Birth of a Nation", 
"Intolerance: Love's Struggle Throughout the Ages", 
"Broken Blossoms", 
"The Cabinet of Dr. Caligari", 
"Way Down East", 
"Within Our Gates", 
"Orphans of the Storm", 
"The Boat", 
"The Phantom Carriage", 
"Dr. Mabuse, the Gambler", 
"Foolish Wives", 
"Nanook of the North", 
"Nosferatu", 
"The Smiling Madame Beudet", 
"Häxan", 
"Our Hospitality", 
"The Wheel", 
"Greed", 
"Sherlock, Jr.", 
"Strike", 
"The Great White Silence", 
"The Last Laugh", 
"The Thief of Bagdad", 
"Battleship Potemkin", 
"Seven Chances", 
"The Big Parade", 
"The Eagle", 
"The Gold Rush", 
"The Phantom of the Opera", 
"The Adventures of Prince Achmed", 
"Metropolis", 
"Napoleon", 
"October", 
"Sunrise", 
"The General", 
"The Jazz Singer", 
"The Kid Brother", 
"The Unknown", 
"Steamboat Bill, Jr.", 
"Storm Over Asia", 
"The Crowd", 
"The Docks of New York", 
"The Passion of Joan of Arc", 
"Un Chien Andalou", 
"A Throw of Dice", 
"Blackmail", 
"Man with a Movie Camera", 
"Pandora's Box", 
"All Quiet on the Western Front", 
"Earth", 
"L'Age d'Or", 
"The Blue Angel", 
"À Nous la Liberté", 
"City Lights", 
"Dracula", 
"Frankenstein", 
"Limite", 
"Little Caesar", 
"M", 
"Tabu", 
"The Bitch", 
"The Million", 
"The Public Enemy", 
"Boudu Saved from Drowning", 
"Freaks", 
"I Am a Fugitive From a Chain Gang", 
"Love Me Tonight", 
"Me and My Gal", 
"Scarface", 
"Shanghai Express", 
"The Vampire", 
"Trouble in Paradise", 
"42nd Street", 
"Duck Soup", 
"Footlight Parade", 
"Gold Diggers of 1933", 
"King Kong", 
"Las Hurdes", 
"Queen Christina", 
"She Done Him Wrong", 
"Sons of the Desert", 
"The Bitter Tea of General Yen", 
"Zero for Conduct", 
"It Happened One Night", 
"It's a Gift", 
"Judge Priest", 
"L'Atalante", 
"The Black Cat", 
"The Goddess", 
"The Thin Man", 
"Triumph of the Will", 
"A Night at the Opera", 
"Bride of Frankenstein", 
"Captain Blood", 
"Mutiny on the Bounty", 
"Peter Ibbetson", 
"The 39 Steps", 
"Top Hat", 
"A Day in the Country", 
"Camille", 
"Dodsworth", 
"Modern Times", 
"Mr. Deeds Goes to Town", 
"My Man Godfrey", 
"Sabotage", 
"Swing Time", 
"The Story of a Cheat", 
"The Wind Will Carry Us", 
"Things to Come", 
"Captains Courageous", 
"La Grande Illusion", 
"Make Way for Tomorrow", 
"Pépé le Moko", 
"Snow White and the Seven Dwarfs", 
"Song at Midnight", 
"Stella Dallas", 
"The Awful Truth", 
"The Life of Emile Zola", 
"Angels with Dirty Faces", 
"Bringing Up Baby", 
"Jezebel", 
"Olympia Part One: Festival of the Nations", 
"Olympia Part Two: Festival of Beauty", 
"The Adventures of Robin Hood", 
"The Baker's Wife", 
"The Lady Vanishes", 
"Babes in Arms", 
"Daybreak", 
"Destry Rides Again", 
"Gone With the Wind", 
"Gunga Din", 
"Mr. Smith Goes to Washington", 
"Ninotchka", 
"Only Angels Have Wings", 
"Stagecoach", 
"The Rules of the Game", 
"The Story of the Last Chrysanthemum", 
"The Wizard of Oz", 
"Wuthering Heights", 
"Dance, Girl, Dance", 
"Fantasia", 
"His Girl Friday", 
"Pinocchio", 
"Rebecca", 
"The Bank Dick", 
"The Grapes of Wrath", 
"The Mortal Storm", 
"The Philadelphia Story", 
"Citizen Kane", 
"Dumbo", 
"High Sierra", 
"How Green Was My Valley", 
"Sergeant York", 
"Sullivan's Travels", 
"The Lady Eve", 
"The Maltese Falcon", 
"The Wolf Man", 
"Casablanca", 
"Cat People", 
"Mrs. Miniver", 
"Now, Voyager", 
"The Magnificent Ambersons", 
"The Palm Beach Story", 
"To Be Or Not To Be", 
"Yankee Doodle Dandy", 
"Fires Were Started", 
"I Walked with a Zombie", 
"Meshes of the Afternoon", 
"Ossessione", 
"Shadow of a Doubt", 
"The Life and Death of Colonel Blimp", 
"The Man in Grey", 
"The Ox-Bow Incident", 
"The Seventh Victim", 
"Double Indemnity", 
"Gaslight", 
"Henry V", 
"Ivan the Terrible, Part I", 
"Laura", 
"Meet Me in St. Louis", 
"Murder, My Sweet", 
"To Have and Have Not", 
"Brief Encounter", 
"Children of Paradise", 
"Detour", 
"I Know Where I'm Going!", 
"Mildred Pierce", 
"Rome, Open City", 
"San Pietro", 
"Spellbound", 
"The Lost Weekend", 
"A Matter of Life and Death", 
"Beauty and the Beast", 
"Black Narcissus", 
"Gilda", 
"Great Expectations", 
"It's a Wonderful Life", 
"My Darling Clementine", 
"Notorious", 
"Paisan", 
"The Best Years of Our Lives", 
"The Big Sleep", 
"The Killers", 
"The Postman Always Rings Twice", 
"The Stranger", 
"Monsieur Verdoux", 
"Odd Man Out", 
"Out of the Past", 
"The Ghost and Mrs. Muir", 
"Bicycle Thieves", 
"Force of Evil", 
"Letter From an Unknown Woman", 
"Louisiana Story", 
"Red River", 
"Rope", 
"Secret Beyond the Door", 
"Spring in a Small Town", 
"The Lady From Shanghai", 
"The Paleface", 
"The Red Shoes", 
"The Snake Pit", 
"The Treasure of the Sierra Madre", 
"Adam's Rib", 
"Gun Crazy", 
"Kind Hearts and Coronets", 
"On the Town", 
"The Heiress", 
"The Reckless Moment", 
"The Third Man", 
"Whisky Galore!", 
"White Heat", 
"All About Eve", 
"In a Lonely Place", 
"Orpheus", 
"Rashomon", 
"Rio Grande", 
"Sunset Blvd.", 
"The Asphalt Jungle", 
"The Young and the Damned", 
"Winchester '73", 
"A Place in the Sun", 
"A Streetcar Named Desire", 
"Ace in the Hole", 
"An American in Paris", 
"Diary of a Country Priest", 
"Pandora and the Flying Dutchman", 
"Strangers on a Train", 
"The African Queen", 
"The Day the Earth Stood Still", 
"The Lavender Hill Mob", 
"Angel Face", 
"Europe '51", 
"Forbidden Games", 
"High Noon", 
"Singin' In the Rain", 
"The Bad and the Beautiful", 
"The Big Sky", 
"The Golden Coach", 
"The Quiet Man", 
"To Live", 
"Umberto D", 
"Beat the Devil", 
"From Here to Eternity", 
"Gentlemen Prefer Blondes", 
"Journey to Italy", 
"Monsieur Hulot's Holiday", 
"Pickup on South Street", 
"Roman Holiday", 
"Shane", 
"Summer with Monika", 
"The Band Wagon", 
"The Big Heat", 
"The Bigamist", 
"The Earrings of Madame De...", 
"The Naked Spur", 
"Tokyo Story", 
"Ugetsu", 
"Wages of Fear", 
"A Star is Born", 
"Animal Farm", 
"Carmen Jones", 
"Diabolique", 
"Johnny Guitar", 
"On the Waterfront", 
"Rear Window", 
"Salt of the Earth", 
"Sansho the Bailiff", 
"Senso", 
"Seven Brides for Seven Brothers", 
"Seven Samurai", 
"Silver Lode", 
"The Barefoot Contessa", 
"The Road", 
"All That Heaven Allows", 
"Artists and Models", 
"Bad Day at Black Rock", 
"Bob le Flambeur", 
"Guys and Dolls", 
"Hill 24 Doesn't Answer", 
"Kiss Me Deadly", 
"Lola Montès", 
"Marty", 
"Night and Fog", 
"Oklahoma!", 
"Ordet", 
"Pather Panchali", 
"Rebel Without a Cause", 
"Smiles of a Summer Night", 
"The Ladykillers", 
"The Mad Masters", 
"The Man From Laramie", 
"The Man with the Golden Arm", 
"The Night of the Hunter", 
"The Phenix City Story", 
"A Man Escaped", 
"Bigger Than Life", 
"Forbidden Planet", 
"Giant", 
"High Society", 
"Invasion of the Body Snatchers", 
"The Burmese Harp", 
"The Man Who Knew Too Much", 
"The Searchers", 
"The Ten Commandments", 
"The Wrong Man", 
"Written on the Wind", 
"12 Angry Men", 
"An Affair to Remember", 
"Gunfight at the O.K. Corral", 
"Mother India", 
"Nights of Cabiria", 
"Paths of Glory", 
"Sweet Smell of Success", 
"The Bridge on the River Kwai", 
"The Cranes are Flying", 
"The Incredible Shrinking Man", 
"The Seventh Seal", 
"The Unvanquished", 
"Throne of Blood", 
"Wild Strawberries", 
"Ashes and Diamonds", 
"Cairo Station", 
"Dracula", 
"Gigi", 
"Ivan the Terrible, Part II", 
"Man of the West", 
"My Uncle", 
"Some Came Running", 
"The Defiant Ones", 
"The Music Room", 
"Touch of Evil", 
"Vertigo", 
"Anatomy of a Murder", 
"Ben-Hur", 
"Black Orpheus", 
"Floating Weeds", 
"Hiroshima Mon Amour", 
"North by Northwest", 
"Pickpocket", 
"Ride Lonesome", 
"Rio Bravo", 
"Shadows", 
"Some Like It Hot", 
"The 400 Blows", 
"The World of Apu", 
"Black Sunday", 
"Breathless", 
"Eyes Without a Face", 
"La Dolce Vita", 
"Peeping Tom", 
"Psycho", 
"Rocco and his Brothers", 
"Saturday Night and Sunday Morning", 
"Shoot the Piano Player", 
"Spartacus", 
"The Adventure", 
"The Apartment", 
"The Cloud-Capped Star", 
"The Hole", 
"The Housemaid", 
"The Young One", 
"Breakfast at Tiffany's", 
"Chronicle of a Summer", 
"Last Year at Marienbad", 
"Lola", 
"One-Eyed Jacks", 
"Splendor in the Grass", 
"The Exiles", 
"The Hustler", 
"The Ladies Man", 
"The Night", 
"Through a Glass Darkly", 
"Viridiana", 
"West Side Story", 
"An Autumn Afternoon", 
"Cleo From 5 to 7", 
"Dog Star Man", 
"Heaven and Earth Magic", 
"Jules and Jim", 
"Lawrence of Arabia", 
"Lolita", 
"Mondo Cane", 
"The Eclipse", 
"The Exterminating Angel", 
"The Given Word", 
"The Man Who Shot Liberty Valance", 
"The Manchurian Candidate", 
"The Pier", 
"To Kill a Mockingbird", 
"Vivre sa Vie", 
"What Ever Happened to Baby Jane?", 
"8.5", 
"An Actor's Revenge", 
"Barren Lives", 
"Blonde Cobra", 
"Contempt", 
"Flaming Creatures", 
"Hud", 
"Méditerranée", 
"Passenger", 
"Shock Corridor", 
"The Birds", 
"The Cool World", 
"The Great Escape", 
"The Haunting", 
"The House is Black", 
"The Leopard", 
"The Nutty Professor", 
"The Servant", 
"Winter Light", 
"A Hard Day's Night", 
"Before the Revolution", 
"Black God, White Devil", 
"Dr. Strangelove, or: How I Learned to Stop Worrying and Love the Bomb", 
"Gertrud", 
"Goldfinger", 
"Marnie", 
"Mary Poppins", 
"My Fair Lady", 
"Red Desert", 
"Scorpio Rising", 
"Shadows of Forgotten Ancestors", 
"The Demon", 
"The Gospel According to St. Matthew", 
"The Masque of the Red Death", 
"The Umbrellas of Cherbourg", 
"Woman in the Dunes", 
"Alphaville", 
"Chimes at Midnight", 
"Doctor Zhivago", 
"Faster, Pussycat! Kill! Kill!", 
"Juliet of the Spirits", 
"Pierrot le Fou", 
"Repulsion", 
"Subarnarekha", 
"The Battle of Algiers", 
"The Man Who Had His Hair Cut Short", 
"The Saragossa Manuscript", 
"The Shop on Main Street", 
"The Sound of Music", 
"The War Game", 
"Tokyo Olympiad", 
"Vinyl", 
"Au Hasard Balthazar", 
"Blow-Up", 
"Come Drink With Me", 
"Daisies", 
"Hold Me While I'm Naked", 
"Masculin Féminin", 
"Persona", 
"Seconds", 
"The Good, the Bad, and the Ugly", 
"Who's Afraid of Virginia Woolf?", 
"2 or 3 Things I Know About Her", 
"Belle de Jour", 
"Bonnie and Clyde", 
"Closely Watched Trains", 
"Cool Hand Luke", 
"Entranced Earth", 
"Hombre", 
"In the Heat of the Night", 
"Marketa Lazarová", 
"Playtime", 
"Point Blank", 
"Report", 
"The Firemen's Ball", 
"The Godson", 
"The Graduate", 
"The Jungle Book", 
"The Red and the White", 
"The Young Girls of Rochefort", 
"Viy", 
"Wavelength", 
"Weekend", 
"2001: A Space Odyssey", 
"Andrei Rublev", 
"David Holzman's Diary", 
"Faces", 
"Fellini Satyricon", 
"High School", 
"Hour of the Wolf", 
"If...", 
"Memories of Underdevelopment", 
"Night of the Living Dead", 
"Once Upon a Time in the West", 
"Planet of the Apes", 
"Rosemary's Baby", 
"Skammen", 
"Targets", 
"The Color of Pomegranates", 
"The Producers", 
"Z", 
"A Touch of Zen", 
"Butch Cassidy and the Sundance Kid", 
"Easy Rider", 
"In the Year of the Pig", 
"Kes", 
"Lucía", 
"Midnight Cowboy", 
"My Night at Maud's", 
"The Cow", 
"The Wild Bunch", 
"Deep End", 
"El Topo", 
"Five Easy Pieces", 
"Gimme Shelter", 
"Little Big Man", 
"MASH", 
"Patton", 
"Performance", 
"The Bird with the Crystal Plumage", 
"The Butcher", 
"The Conformist", 
"The Ear", 
"The Garden of the Finzi-Continis", 
"The Spider's Stratagem", 
"Tristana", 
"Woodstock", 
"Zabriskie Point", 
"A Clockwork Orange", 
"Dirty Harry", 
"Get Carter", 
"Harold and Maude", 
"Klute", 
"McCabe & Mrs. Miller", 
"Murmur of the Heart", 
"Red Psalm", 
"Shaft", 
"Straw Dogs", 
"Sweet Sweetback's Baadasssss Song", 
"The Devils", 
"The French Connection", 
"The Hired Hand", 
"The Last Picture Show", 
"The Sorrow and the Pity", 
"Two-Lane Blacktop", 
"W.R.: Mysteries of the Organism", 
"Wake in Fright", 
"Walkabout", 
"Wanda", 
"Willy Wonka & the Chocolate Factory", 
"Aguirre, the Wrath of God", 
"Cabaret", 
"Cries & Whispers", 
"Deliverance", 
"Fat City", 
"Frenzy", 
"Last Tango in Paris", 
"Pink Flamingos", 
"Sleuth", 
"Solaris", 
"Superfly", 
"The Bitter Tears of Petra Von Kant", 
"The Discreet Charm of the Bourgeoisie", 
"The Godfather", 
"The Heartbreak Kid", 
"Amarcord", 
"American Graffiti", 
"Badlands", 
"Day for Night", 
"Don't Look Now", 
"Enter the Dragon", 
"F for Fake", 
"Fantastic Planet", 
"High Plains Drifter", 
"Papillon", 
"Pat Garrett & Billy the Kid", 
"Serpico", 
"Sleeper", 
"Streets", 
"The Exorcist", 
"The Harder They Come", 
"The Long Goodbye", 
"The Mother and the Whore", 
"The Spirit of the Beehive", 
"The Sting", 
"The Wicker Man", 
"Turkish Delight", 
"A Woman Under the Influence", 
"Ali: Fear Eats the Soul", 
"Blazing Saddles", 
"Bring Me the Head of Alfredo Garcia", 
"Celine and Julie Go Boating", 
"Chinatown", 
"Dersu Uzala", 
"The Conversation", 
"The Godfather: Part II", 
"The Mirror", 
"The Texas Chain Saw Massacre", 
"The Towering Inferno", 
"Young Frankenstein", 
"Barry Lyndon", 
"Cria!", 
"Dog Day Afternoon", 
"Fox and his Friends", 
"India Song", 
"Jaws", 
"Jeanne Dielman, 23 Quai du Commerce, 1080 Bruxelles", 
"Manila in the Claws of Light", 
"Monty Python and the Holy Grail", 
"Nashville", 
"One Flew Over the Cuckoo's Nest", 
"Picnic at Hanging Rock", 
"Salo, or the 120 Days of Sodom", 
"The Rocky Horror Picture Show", 
"The Travelling Players", 
"The Wall", 
"All the President's Men", 
"Carrie", 
"In the Realm of the Senses", 
"Network", 
"Novecento", 
"Rocky", 
"Taxi Driver", 
"The Killing of a Chinese Bookie", 
"The Man Who Fell to Earth", 
"The Outlaw Josey Wales", 
"Annie Hall", 
"Ascent", 
"Ceddo", 
"Close Encounters of the Third Kind", 
"Eraserhead", 
"Killer of Sheep", 
"Last Chants for a Slow Dance", 
"Man of Marble", 
"Saturday Night Fever", 
"Sleeping Dogs", 
"Soldier of Orange", 
"Star Wars", 
"Stroszek", 
"Suspiria", 
"The American Friend", 
"The Hills Have Eyes", 
"The Last Wave", 
"Dawn of the Dead", 
"Days of Heaven", 
"Five Deadly Venoms", 
"Grease", 
"Halloween", 
"The 36th Chamber of Shaolin", 
"The Chant of Jimmie Blacksmith", 
"The Deer Hunter", 
"The Tree of Wooden Clogs", 
"Up in Smoke", 
"Alien", 
"All That Jazz", 
"Apocalypse Now", 
"Being There", 
"Breaking Away", 
"Christ Stopped at Eboli", 
"Kramer vs. Kramer", 
"Life of Brian", 
"Mad Max", 
"Manhattan", 
"My Brilliant Career", 
"Nosferatu the Vampyre", 
"Real Life", 
"Stalker", 
"The Jerk", 
"The Marriage of Maria Braun", 
"The Muppet Movie", 
"The Tin Drum", 
"Airplane!", 
"Atlantic City", 
"Loulou", 
"Ordinary People", 
"Raging Bull", 
"Star Wars: Episode V - The Empire Strikes Back", 
"The Big Red One", 
"The Elephant Man", 
"The Last Metro", 
"The Shining", 
"An American Werewolf in London", 
"Body Heat", 
"Chariots of Fire", 
"Diva", 
"Gallipoli", 
"Man of Iron", 
"Raiders of the Lost Ark", 
"Reds", 
"Three Brothers", 
"A Question of Silence", 
"Blade Runner", 
"Diner", 
"E.T.: The Extra-Terrestrial", 
"Fanny and Alexander", 
"Fast Times at Ridgemont High", 
"Fitzcarraldo", 
"Gandhi", 
"Poltergeist", 
"The Draughtsman's Contract", 
"The Evil Dead", 
"The Night of the Shooting Stars", 
"The Thing", 
"Too Early, Too Late", 
"Tootsie", 
"Yol", 
"A Christmas Story", 
"El Norte", 
"Koyaanisqatsi", 
"Local Hero", 
"Money", 
"Sans Soleil", 
"Scarface", 
"Star Wars: Episode VI - Return of the Jedi", 
"Terms of Endearment", 
"The Ballad of Narayama", 
"The Big Chill", 
"The Fourth Man", 
"The King of Comedy", 
"The Last Battle", 
"The Right Stuff", 
"Videodrome", 
"A Nightmare on Elm Street", 
"A Passage to India", 
"Amadeus", 
"Beverly Hills Cop", 
"Ghostbusters", 
"Once Upon a Time in America", 
"Paris, Texas", 
"Stranger than Paradise", 
"The Killing Fields", 
"The Natural", 
"The Terminator", 
"This is Spinal Tap", 
"Utu", 
"A Room with a View", 
"A Time to Live and a Time to Die", 
"Back to the Future", 
"Brazil", 
"Come and See", 
"Kiss of the Spider Woman", 
"Mishima: A Life in Four Chapters", 
"Out of Africa", 
"Prizzi's Honor", 
"Ran", 
"Shoah", 
"The Breakfast Club", 
"The Color Purple", 
"The Official Story", 
"The Purple Rose of Cairo", 
"The Quiet Earth", 
"Vagabond", 
"Aliens", 
"Blue Velvet", 
"Caravaggio", 
"Children of a Lesser God", 
"Down By Law", 
"Ferris Bueller's Day Off", 
"Hannah and Her Sisters", 
"Manhunter", 
"Peking Opera Blues", 
"Platoon", 
"Salvador", 
"She's Gotta Have It", 
"Sherman's March", 
"Stand By Me", 
"Tampopo", 
"The Decline of the American Empire", 
"The Fly", 
"The Horse Thief", 
"Top Gun", 
"A Chinese Ghost Story", 
"Au Revoir les Enfants", 
"Babette's Feast", 
"Brightness", 
"Broadcast News", 
"Fatal Attraction", 
"Full Metal Jacket", 
"Good Morning, Vietnam", 
"Housekeeping", 
"Moonstruck", 
"Project A 2", 
"Raising Arizona", 
"Red Sorghum", 
"RoboCop", 
"The Dead", 
"The Princess Bride", 
"The Untouchables", 
"Wall Street", 
"Wings of Desire", 
"Withnail & I", 
"A Fish Called Wanda", 
"A Tale of the Wind", 
"Akira", 
"Alice", 
"Ariel", 
"Big", 
"Bull Durham", 
"Cinema Paradiso", 
"Dangerous Liaisons", 
"Dead Ringers", 
"Dekalog (Series)", 
"Die Hard", 
"Distant Voices, Still Lives", 
"Drowning By Numbers", 
"Grave of the Fireflies", 
"Hotel Terminus", 
"Landscape in the Mist", 
"Rain Man", 
"Story of Women", 
"The Accidental Tourist", 
"The Naked Gun", 
"The Thin Blue Line", 
"The Vanishing", 
"Who Framed Roger Rabbit?", 
"Women on the Verge of a Nervous Breakdown", 
"A City of Sadness", 
"Batman", 
"Crimes and Misdemeanors", 
"Do the Right Thing", 
"Drugstore Cowboy", 
"Field of Dreams", 
"Glory", 
"My Left Foot", 
"Roger & Me", 
"Say Anything", 
"Sex, Lies, and Videotape", 
"The Asthenic Syndrome", 
"The Cook, the Thief, His Wife, & Her Lover", 
"The Killer", 
"The Unbelievable Truth", 
"When Harry Met Sally...", 
"Archangel", 
"Close-Up", 
"Dances with Wolves", 
"Edward Scissorhands", 
"Europa Europa", 
"Goodfellas", 
"Henry: Portrait of a Serial Killer", 
"Jacob's Ladder", 
"King of New York", 
"No Fear, No Die", 
"Pretty Woman", 
"Reversal of Fortune", 
"Total Recall", 
"Trust", 
"A Brighter Summer Day", 
"Boyz 'N the Hood", 
"Delicatessen", 
"Hearts of Darkness: A Filmmaker's Apocalypse", 
"JFK", 
"La Belle Noiseuse", 
"My Own Private Idaho", 
"Naked Lunch", 
"Once Upon a Time in China", 
"Raise the Red Lantern", 
"Slacker", 
"Terminator 2: Judgment Day", 
"The Double Life of Veronique", 
"The Rapture", 
"The Silence of the Lambs", 
"Thelma & Louise", 
"Tongues Untied", 
"A Tale of Winter", 
"Aileen Wuornos: The Selling of a Serial Killer", 
"Bram Stoker's Dracula", 
"Candyman", 
"Glengarry Glen Ross", 
"Man Bites Dog", 
"Reservoir Dogs", 
"Romper Stomper", 
"Strictly Ballroom", 
"The Actress", 
"The Crying Game", 
"The Player", 
"Unforgiven", 
"Farewell My Concubine", 
"Groundhog Day", 
"Jurassic Park", 
"Philadelphia", 
"Schindler's List", 
"Short Cuts", 
"The Age of Innocence", 
"The Blue Kite", 
"The Piano", 
"The Puppetmaster", 
"The Wedding Banquet", 
"Thirty Two Short Films About Glenn Gould", 
"Three Colors: Blue", 
"Chungking Express", 
"Clerks", 
"Crumb", 
"Dear Diary", 
"Forrest Gump", 
"Four Weddings and a Funeral", 
"Heavenly Creatures", 
"Hoop Dreams", 
"Muriel's Wedding", 
"Natural Born Killers", 
"Pulp Fiction", 
"Sátántangó", 
"The Adventures of Priscilla, Queen of the Desert", 
"The Kingdom", 
"The Last Seduction", 
"The Lion King", 
"The Shawshank Redemption", 
"Three Colors: Red", 
"Through the Olive Trees", 
"Wild Reeds", 
"Babe", 
"Braveheart", 
"Casino", 
"Clueless", 
"Cyclo", 
"Dead Man", 
"Deseret", 
"Dilwale Dulhania Le Jayenge", 
"Heat", 
"Safe", 
"Se7en", 
"Smoke", 
"Strange Days", 
"The Usual Suspects", 
"The White Balloon", 
"Toy Story", 
"Underground", 
"Zero Kelvin", 
"Breaking the Waves", 
"Fargo", 
"Gabbeh", 
"Independence Day", 
"Lone Star", 
"Scream", 
"Secrets & Lies", 
"Shine", 
"The English Patient", 
"Three Lives and Only One Death", 
"Trainspotting", 
"Boogie Nights", 
"Deconstructing Harry", 
"Fast, Cheap & Out of Control", 
"Fireworks", 
"Funny Games", 
"Happy Together", 
"Kundun", 
"L.A. Confidential", 
"Mother and Son", 
"Open Your Eyes", 
"Princess Mononoke", 
"Taste of Cherry", 
"The Butcher Boy", 
"The Ice Storm", 
"The Pillow Book", 
"The Sweet Hereafter", 
"Titanic", 
"Buffalo '66", 
"Happiness", 
"Lock, Stock, and Two Smoking Barrels", 
"Pi", 
"Ring", 
"Run Lola Run", 
"Rushmore", 
"Saving Private Ryan", 
"Sombre", 
"Tetsuo", 
"The Big Lebowski", 
"The Celebration", 
"The Idiots", 
"The Thin Red Line", 
"There's Something About Mary", 
"All About My Mother", 
"American Beauty", 
"Attack the Gas Station", 
"Audition", 
"Beau Travail", 
"Being John Malkovich", 
"Eyes Wide Shut", 
"Fight Club", 
"Magnolia", 
"Rosetta", 
"Taboo", 
"The Blair Witch Project", 
"The Matrix", 
"The Sixth Sense", 
"Three Kings", 
"Time Regained", 
"Toy Story 2", 
"Ali Zaoua, Prince of the Streets", 
"Amores Perros", 
"Crouching Tiger, Hidden Dragon", 
"Dancer in the Dark", 
"Gladiator", 
"In the Mood for Love", 
"Kippur", 
"Meet the Parents", 
"Memento", 
"Nine Queens", 
"O Brother, Where Art Thou?", 
"Requiem for a Dream", 
"Signs & Wonders", 
"The Captive", 
"The Gleaners and I", 
"Traffic", 
"Yi Yi", 
"A.I.: Artificial Intelligence", 
"Amélie", 
"Fat Girl", 
"Kandahar", 
"Lantana", 
"Monsoon Wedding", 
"Moulin Rouge!", 
"Mulholland Drive", 
"No Man's Land", 
"Spirited Away", 
"The Lord of the Rings: The Fellowship of the Ring", 
"The Piano Teacher", 
"The Royal Tenenbaums", 
"The Son's Room", 
"What Time Is It There?", 
"Y Tu Mamá También", 
"Adaptation.", 
"Bowling for Columbine", 
"Bus 174", 
"Chicago", 
"City of God", 
"Distant", 
"Far from Heaven", 
"Gangs of New York", 
"Hero", 
"Irreversible", 
"Rabbit-Proof Fence", 
"Russian Ark", 
"Talk to Her", 
"The Lord of the Rings: The Two Towers", 
"The Pianist", 
"Aileen: Life and Death of a Serial Killer", 
"Elephant", 
"Good Bye, Lenin!", 
"Kill Bill, Vol. 1", 
"Lost in Translation", 
"Oldboy", 
"Osama", 
"The Barbarian Invasions", 
"The Best of Youth", 
"The Lord of the Rings: The Return of the King", 
"3-Iron", 
"A Very Long Engagement", 
"Collateral", 
"Crash", 
"Downfall", 
"Fahrenheit 9/11", 
"Head-On", 
"Million Dollar Baby", 
"Moolaadé", 
"Sideways", 
"The Aviator", 
"The Consequences of Love", 
"The Passion of the Christ", 
"Brokeback Mountain", 
"Hidden", 
"Live and Become", 
"Paradise Now", 
"The Constant Gardener", 
"Tsotsi", 
"Apocalypto", 
"Babel", 
"Borat", 
"Children of Men", 
"Little Miss Sunshine", 
"Once", 
"Pan's Labyrinth", 
"The Departed", 
"The Host", 
"The Last King of Scotland", 
"The Lives of Others", 
"The Prestige", 
"The Queen", 
"United 93", 
"Volver", 
"Atonement", 
"Into the Wild", 
"La Vie en Rose", 
"No Country for Old Men", 
"Paranormal Activity", 
"Surfwise", 
"The Bourne Ultimatum", 
"The Diving Bell and the Butterfly", 
"There Will Be Blood", 
"Anvil: The Story of Anvil", 
"Gomorrah", 
"Let the Right One In", 
"Slumdog Millionaire", 
"The Class", 
"The Curious Case of Benjamin Button", 
"The Dark Knight", 
"The Good, the Bad, the Weird", 
"The Hurt Locker", 
"The Wrestler", 
"Wall-E", 
"An Education", 
"Avatar", 
"District 9", 
"Fish Tank", 
"In the Loop", 
"Inglourious Basterds", 
"Precious", 
"The Hangover", 
"The White Ribbon", 
"Black Swan", 
"Cave of Forgotten Dreams", 
"Four Lions", 
"Inception", 
"Monsters", 
"Nostalgia for the Light", 
"Of Gods and Men", 
"Senna", 
"The King's Speech", 
"The Social Network", 
"Toy Story 3", 
"True Grit", 
"A Separation", 
"Bridesmaids", 
"Drive", 
"Hugo", 
"Le Havre", 
"Shame", 
"The Artist", 
"The Descendants", 
"The Girl with the Dragon Tattoo", 
"The Kid with a Bike", 
"The Tree of Life", 
"Tinker Tailor Soldier Spy", 
"War Horse", 
"Amour", 
"Argo", 
"Blancanieves", 
"Django Unchained", 
"Les Misérables", 
"Life of Pi", 
"Lincoln", 
"Skyfall", 
"The Act of Killing", 
"The Cabin in the Woods", 
"Wadjda", 
"12 Years a Slave", 
"A Touch of Sin", 
"American Hustle", 
"Blue is the Warmest Colour", 
"Gravity", 
"Ida", 
"Inside Llewyn Davis", 
"Nebraska", 
"The Great Beauty", 
"The Wolf of Wall Street", 
"Under the Skin", 
"Birdman", 
"Boyhood", 
"Citizenfour", 
"Guardians of the Galaxy", 
"Leviathan", 
"The Grand Budapest Hotel", 
"The Theory of Everything", 
"Whiplash", 
"Bridge of Spies", 
"I, Daniel Blake", 
"Jackie", 
"Mad Max Fury Road", 
"Son of Saul", 
"Spotlight", 
"Star Wars: Episode VII - The Force Awakens", 
"Straight Outta Compton", 
"Tangerine", 
"The Big Short", 
"The Look of Silence", 
"The Revenant", 
"Under the Shadow", 
"Victoria", 
"13th", 
"Arrival", 
"Dawson City: Frozen Time", 
"Hell or High Water", 
"La La Land", 
"Lady Macbeth", 
"Manchester by the Sea", 
"Moonlight", 
"The Handmaiden", 
"The Jungle Book", 
"Toni Erdmann", 
"Blade Runner 2049", 
"Call Me By Your Name", 
"Get Out", 
"Lady Bird", 
"Mother!", 
"The Shape of Water", 
"Three Billboards Outside Ebbing, Missouri", 
"Black Panther", 
"A Star is Born", 
"Avengers: Infinity War", 
"BlacKkKlansman", 
"Capernaum", 
"Crazy Rich Asians", 
"Hereditary", 
"Phantom Thread", 
"Roma", 
"Sorry to Bother You", 
"The Favourite", 
"The Greatest Showman", 
"Vice"
];

function randomMovie () {
    let i = Math.floor(Math.random() * moviesArray.length);
    return moviesArray[i];
}


export default randomMovie;